### ISSUE TITLE
Plaatjes drankjes

### ISSUE THREAD

**Issue by abihas** [rtenklooster/webprogrammeren#1]

**Comment by mt5thomas** [comment]
Ik zag deze issue openstaan, en ga ervan uit dat er betere plaatjes voor de dranken moeten komen, ik heb al een 4 tal nieuwe geupload naar de gedeelde map in onedrive, denk dat deze wat netter zijn.

gr, thomas

**Comment by pawesseling** [comment]
had er ook even nagekeken , heb er nieuwe ingezet op GIT . Moeten even kijken welke mooier zijn . Blikjes of de flesjes die er nu staan.
