### ISSUE TITLE
check sql afsluiten

### ISSUE THREAD

**Issue by abihas** [rtenklooster/webprogrammeren#10]

**Comment by rtenklooster** [comment]
According to documentation you're correct (http://php.net/manual/en/pdo.connections.php):

    The connection remains active for the lifetime of that PDO object. To close the connection, you need to destroy the object by ensuring that all remaining references to it are deleted--you do this by assigning NULL to the variable that holds the object. **If you don't do this explicitly, PHP will automatically close the connection when your script ends.**
